version: '3.8'
services:
  app:
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - llama_models:/app/models
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/biztools
      - NODE_ENV=development
      - LLAMA_MODEL_PATH=/app/models/llama-2-7b-chat.gguf
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=biztools
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  model_downloader:
    image: alpine:latest
    volumes:
      - llama_models:/models
    command: >
      wget -O /models/llama-2-7b-chat.gguf https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf
    restart: on-failure

volumes:
  postgres_data:
  llama_models: 